[versions]
agp = "8.13.1"
kotlin = "2.0.21"

junit = "4.13.2"
junitExt = "1.3.0"
espressoCore = "3.7.0"

appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
lifecycleRuntimeKtx = "2.6.1"

activityCompose = "1.8.0"
composeBom = "2024.09.00"

[libraries]
# Android base
appcompatLib = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
materialLib = { group = "com.google.android.material", name = "material", version.ref = "material" }
activityLib = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayoutLib = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Lifecycle
lifecycleRuntimeKtxLib = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Compose
activityComposeLib = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
composeBomLib = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

ui = { group = "androidx.compose.ui", name = "ui" }
uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Testes
junit = { group = "junit", name = "junit", version.ref = "junit" }
extJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
espressoCoreLib = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
